### ISSUE TITLE
Some work already done in https://github.com/iansu/eslint-plugin-node-core

### ISSUE THREAD

**Issue by nschonni** [nodejs/eslint-plugin-nodejs-internal#5]
Looks like this was prepared for import into the pkgjs org https://github.com/iansu/eslint-plugin-node-core

**Comment by nschonni** [comment]
@iansu I synced across your initial setup as the starting commit. Did you want to join the @nodejs/linting and contribute there?

**Comment by iansu** [comment]
Sure! I think it would be great to publish this plugin directly from the nodejs org. I was hoping that was the case originally and then I wouldn't have had to do any additional work. What exactly do you need me to do?

**Comment by nschonni** [comment]
Trying to get a CI setup against core going in https://github.com/nodejs/eslint-plugin-nodejs-internal/pull/6 but hitting some issues. Not sure what stuff you already encountered and figured out

**Comment by Trott** [comment]
(I added iansu to the linteing team.)

**Comment by nschonni** [comment]
Thanks @Trott!
I'm going to close this one since I used that repo for the base commit, and we can keep working with the other issues
